### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by petervalencic**
- windows build tools for npm

### CODE REVIEW

**Comment by petervalencic** [comment]
Got this error if get Scatter from git and run npm install:

C:\Scatter>npm install

> sha3@1.2.1 install C:\Scatter\node_modules\sha3
> node-gyp rebuild


C:\Scatter\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gy
p\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:170:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Scatter\node_modules\sha3
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN scatter@4.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\peterv.IN2KOPER\AppData\Roaming\npm-cache\_logs\2018-05-09T06_46_15_849Z-debug.log

**Comment by petervalencic** [comment]
after that:

C:\Scatter>npm install --global --production windows-build-tools

> windows-build-tools@2.3.0 postinstall C:\Users\peterv.IN2KOPER\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.14.amd64.msi
[============================================>] 100.0% of 20.17 MB (3.84 MB/s)
Downloaded python-2.7.14.amd64.msi. Saved to C:\Users\peterv.IN2KOPER\.windows-build-tools\python-2.7.14.amd64.msi.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Successfully installed Python 2.7
+ windows-build-tools@2.3.0
added 147 packages in 489.552s

**Comment by petervalencic** [comment]
And then:

C:\Scatter>npm install

> sha3@1.2.1 install C:\Scatter\node_modules\sha3
> node-gyp rebuild


C:\Scatter\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gy
p\bin\node-gyp.js" rebuild )  else (node "C:\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cpp
  displayIntermediateValues.cpp
  KeccakF-1600-reference.cpp
  KeccakNISTInterface.cpp
  KeccakSponge.cpp
  win_delay_load_hook.cc
..\src\addon.cpp(49): warning C4316: 'SHA3Hash': object allocated on the heap may not be aligned 32 [C:\Scatter\node_modules\sha3\build\sha3.vcxproj]
     Creating library C:\Scatter\node_modules\sha3\build\Release\sha3.lib and object C:\Scatter\node_modules\sha3\build\Release\sha3.exp
  Generating code
  All 189 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  sha3.vcxproj -> C:\Scatter\node_modules\sha3\build\Release\\sha3.node
  sha3.vcxproj -> C:\Scatter\node_modules\sha3\build\Release\sha3.pdb (Full PDB)
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN scatter@4.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 19 packages in 34.522s

**Comment by petervalencic** [comment]
After I got this error:

C:\Scatter>copy .env.example .env
        1 file(s) copied.

C:\Scatter>npm start

> scatter@4.0.0 start C:\Scatter
> set SCATTER_ENV=development&& webpack --watch

development
[hard-source:core] HardSourceWebpackPlugin is writing to a new confighash path for the first time: C:\Scatter\node_modules\.cache\hard-source\ab0924135c71d1119b5e6753d91d3a8536068f88d0d6655a61407d16f2861904

Webpack is watching the files…

Hash: 2ed085ac37532645ec7d
Version: webpack 3.11.0
Time: 23692ms
                                                    Asset       Size  Chunks                    Chunk Names
                 assets/fonts/font-awesome/less/list.less  396 bytes          [emitted]
                                                 popup.js    3.52 MB       0  [emitted]  [big]  popup.js
                                            background.js    2.91 MB       2  [emitted]  [big]  background.js
                                                inject.js    1.82 MB    3, 4  [emitted]  [big]  inject.js
                                           scatterdapp.js    1.81 MB       4  [emitted]  [big]  scatterdapp.js
                                               content.js     678 kB       5  [emitted]  [big]  content.js
                                               styles.css    7.41 kB       6  [emitted]         styles.css
                                             popup.js.map    4.28 MB       0  [emitted]         popup.js
                                            prompt.js.map    4.28 MB       1  [emitted]         prompt.js
                                        background.js.map    3.51 MB       2  [emitted]         background.js
                                            inject.js.map    2.26 MB    3, 4  [emitted]         inject.js
                                       scatterdapp.js.map    2.25 MB       4  [emitted]         scatterdapp.js
                                           content.js.map     828 kB       5  [emitted]         content.js
                                           styles.css.map    2.46 kB       6  [emitted]         styles.css
       assets/fonts/font-awesome/css/font-awesome.min.css    32.4 kB          [emitted]
           assets/fonts/font-awesome/css/font-awesome.css    39.8 kB          [emitted]
 assets/fonts/font-awesome/fonts/fontawesome-webfont.woff      98 kB          [emitted]
assets/fonts/font-awesome/fonts/fontawesome-webfont.woff2    77.2 kB          [emitted]
                assets/fonts/font-awesome/HELP-US-OUT.txt  330 bytes          [emitted]
          assets/fonts/font-awesome/fonts/FontAwesome.otf     135 kB          [emitted]
  assets/fonts/font-awesome/fonts/fontawesome-webfont.eot     166 kB          [emitted]
             assets/fonts/font-awesome/less/animated.less  747 bytes          [emitted]
                 assets/fonts/font-awesome/less/core.less  464 bytes          [emitted]
          assets/fonts/font-awesome/less/fixed-width.less  125 bytes          [emitted]
      assets/fonts/font-awesome/less/bordered-pulled.less  610 bytes          [emitted]
               assets/fonts/font-awesome/less/larger.less  383 bytes          [emitted]
         assets/fonts/font-awesome/less/font-awesome.less  513 bytes          [emitted]
                                                prompt.js    3.51 MB       1  [emitted]  [big]  prompt.js
               assets/fonts/font-awesome/less/mixins.less    1.66 kB          [emitted]
                 assets/fonts/font-awesome/less/path.less  786 bytes          [emitted]
                assets/fonts/font-awesome/less/icons.less    50.5 kB          [emitted]
      assets/fonts/font-awesome/less/rotated-flipped.less  642 bytes          [emitted]
        assets/fonts/font-awesome/less/screen-reader.less  123 bytes          [emitted]
              assets/fonts/font-awesome/less/stacked.less  496 bytes          [emitted]
     assets/fonts/font-awesome/scss/_bordered-pulled.scss  617 bytes          [emitted]
            assets/fonts/font-awesome/scss/_animated.scss  749 bytes          [emitted]
                assets/fonts/font-awesome/scss/_core.scss  471 bytes          [emitted]
         assets/fonts/font-awesome/scss/_fixed-width.scss  126 bytes          [emitted]
              assets/fonts/font-awesome/scss/_larger.scss  388 bytes          [emitted]
            assets/fonts/font-awesome/less/variables.less    23.4 kB          [emitted]
                assets/fonts/font-awesome/scss/_list.scss  397 bytes          [emitted]
              assets/fonts/font-awesome/scss/_mixins.scss     1.7 kB          [emitted]
                assets/fonts/font-awesome/scss/_path.scss  798 bytes          [emitted]
               assets/fonts/font-awesome/scss/_icons.scss    51.3 kB          [emitted]
       assets/fonts/font-awesome/scss/_screen-reader.scss  139 bytes          [emitted]
     assets/fonts/font-awesome/scss/_rotated-flipped.scss  692 bytes          [emitted]
             assets/fonts/font-awesome/scss/_stacked.scss  502 bytes          [emitted]
         assets/fonts/font-awesome/scss/font-awesome.scss  448 bytes          [emitted]
                                                 icon.png    14.1 kB          [emitted]
                                               index.html  673 bytes          [emitted]
           assets/fonts/font-awesome/scss/_variables.scss    23.4 kB          [emitted]
                                            manifest.json  750 bytes          [emitted]
  assets/fonts/font-awesome/fonts/fontawesome-webfont.svg     447 kB          [emitted]  [big]
  assets/fonts/font-awesome/fonts/fontawesome-webfont.ttf     166 kB          [emitted]
                                              prompt.html  623 bytes          [emitted]
  [20] ./src/store/constants.js 757 bytes {0} {1} {2} [built]
  [49] ./src/models/Network.js 928 bytes {0} {1} {2} {3} {4} {5} [built]
  [50] ./src/models/Identity.js 9.98 kB {0} {1} {2} {3} {4} [built]
 [183] ./src/models/Permission.js 1.13 kB {0} {1} {2} [built]
[1011] ./src/scatterdapp.js 6.45 kB {3} {4} [built]
[1018] ./src/background.js 16.6 kB {2} [built]
[1019] ./src/services/SignatureService.js 6.52 kB {2} [built]
[1020] ./src/models/histories/HistoricEvent.js 327 bytes {2} [built]
[1021] ./src/popup.js 1.77 kB {0} [built]
[1030] ./src/views/ViewBase.vue 1.86 kB {0} [built]
[1034] ./src/content.js 6.55 kB {5} [built]
[1035] ./src/inject.js 1.11 kB {3} [built]
[1036] ./src/prompt.js 2.11 kB {1} [built]
[1037] ./src/prompts/PromptBase.vue 1.87 kB {1} [built]
[1046] ./src/styles.scss 4.89 kB {6} [built] [failed] [1 error]
    + 1032 hidden modules

ERROR in ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4e8d7ed1","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js
?type=styles&index=0!./src/views/MainMenuView.vue
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Scatter\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.getInstalledBinaries (C:\Scatter\node_modules\node-sass\lib\extensions.js:129:13)
    at foundBinariesList (C:\Scatter\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Scatter\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Scatter\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Scatter\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Scatter\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Scatter\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Scatter\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Scatter\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Scatter\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Scatter\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Scatter\node_modules\webpack\lib\NormalModule.js:182:3)
    at NormalModule.build (C:\Scatter\node_modules\webpack\lib\NormalModule.js:275:15)
    at Compilation.buildModule (C:\Scatter\node_modules\webpack\lib\Compilation.js:151:10)
 @ ./node_modules/vue-style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4e8d7ed1","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/
vue-loader/lib/selector.js?type=styles&index=0!./src/views/MainMenuView.vue 4:14-338
 @ ./src/views/MainMenuView.vue
 @ ./src/vue/Routing.js
 @ ./src/popup.js

ERROR in ./node_modules/css-loader!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-35ec55d4","scoped":false,"hasInlineConfig":false}!./node_modules/sass-loader/lib/loader.js!./node_modules/vue-loader/lib/selector.js
?type=styles&index=0!./src/prompts/RequestArbitrarySignaturePrompt.vue
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Scatter\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.getInstalledBinaries (C:\Scatter\node_modules\node-sass\lib\extensions.js:129:13)
    at foundBinariesList (C:\Scatter\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Scatter\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Scatter\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Scatter\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Scatter\node_modules\node-sass\lib\index.js:14:35)

**Comment by nsjames** [comment]
Odd, alright I added it in and referenced this thread. Thanks!

**Pull request merged**
